| a. ¿Qué representa una fila del dataset?                                  | la información de cada estudiante que realizo la encuesta                             |
|---------------------------------------------------------------------------|---------------------------------------------------------------------------------------|
| b. ¿Cuál es la unidad de análisis?                                        | son los estudiantes de la universidad de estudio                                      |
| c. ¿Cuántas observaciones y variables hay?                                | En total encontramos 2512 observaciones y 19 variables que se representan en la tabla |
| d. ¿Qué parece representar el dataset en términos del problema o dominio? |                                                                                       |

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("estudiantes - copy.csv")

In [21]:
df.head()

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04

In [55]:
df.tail()

,variables,tipo_python,escala,descripcion,ejemplo
confianza_programando,confianza_programando,int64,ordinal,0,1
area_interes_datos,area_interes_datos,str,nominal,0,IA y ML
modalidad_preferida,modalidad_preferida,str,ordinal,0,Presencial
promedio_acumulado,promedio_acumulado,float64,discreto,0,3.24
fecha_encuesta,fecha_encuesta,str,nominal,0,2026-08-04

In [8]:
df.shape

(2512, 19)

In [57]:
df.columns

Index(['variables', 'tipo_python', 'escala', 'descripcion', 'ejemplo'], dtype='str')

In [10]:
tipo = df.dtypes
print(tipo)

student_id                       str
programa                         str
semestre                       int64
edad                           int64
genero                           str
horas_estudio_semana         float64
horas_sueno_noche            float64
tiempo_desplazamiento_min    float64
medio_transporte                 str
nivel_estres                   int64
satisfaccion_academica         int64
dias_ejercicio_semana          int64
horas_sociales_semana        float64
uso_ia_generativa                str
confianza_programando          int64
area_interes_datos               str
modalidad_preferida              str
promedio_acumulado           float64
fecha_encuesta                   str
dtype: object

In [11]:

escala = ["ordinal","Nominal","continua","continua","nominal","continua","continua","continua","nominal","ordinal","ordinal","discreto","discreto","ordinal","ordinal","nominal","ordinal","discreto","nominal"]
tipos = ["str","str","int64","int64","str","float64","float64","float64","str","int64","int64","int64","float64","str","int64","str","str","float64","str"]
ejemplo = ["E0456","Administración","2","19","Mujer","17.7","5.8","47.0","Caminando","4","4","3","4.9","Frecuentemente","1","IA y ML","Presencial","3.24","2026-08-04"]
dcd = {
       "variables" : df.columns,
       "tipo_python":tipos,
       "escala": escala,
       "descripcion": 0,
       "ejemplo": ejemplo}

ef = pd.DataFrame(dcd, index = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19] )
ef

,variables,tipo_python,escala,descripcion,ejemplo
1,student_id,str,ordinal,0,E0456
2,programa,str,Nominal,0,Administración
3,semestre,int64,continua,0,2
4,edad,int64,continua,0,19
5,genero,str,nominal,0,Mujer
6,horas_estudio_semana,float64,continua,0,17.7
7,horas_sueno_noche,float64,continua,0,5.8
8,tiempo_desplazamiento_min,float64,continua,0,47.0
9,medio_transporte,str,nominal,0,Caminando
10,nivel_estres,int64,ordinal,0,4
11,satisfaccion_academica,int64,ordinal,0,4
12,dias_ejercicio_semana,int64,discreto,0,3
13,horas_sociales_semana,float64,discreto,0,4.9
14,uso_ia_generativa,str,ordinal,0,Frecuentemente
15,confianza_programando,int64,ordinal,0,1
16,area_interes_datos,str,nominal,0,IA y ML
17,modalidad_preferida,str,ordinal,0,Presencial
18,promedio_acumulado,float64,discreto,0,3.24
19,fecha_encuesta,str,nominal,0,2026-08-04

In [22]:
df.isnull().sum()

student_id                    0
programa                      0
semestre                      0
edad                          0
genero                        0
horas_estudio_semana          0
horas_sueno_noche            72
tiempo_desplazamiento_min    56
medio_transporte              0
nivel_estres                  0
satisfaccion_academica        0
dias_ejercicio_semana         0
horas_sociales_semana         0
uso_ia_generativa             0
confianza_programando         0
area_interes_datos           41
modalidad_preferida           0
promedio_acumulado            0
fecha_encuesta                0
dtype: int64

In [ ]:
variables = df.columns
i = 0
while i < len(variables):
    print( df[i].nunique )
    i += 1

<bound method IndexOpsMixin.nunique of 0       E0001
1       E0002
2       E0003
3       E0004
4       E0005
        ...
2507    E2113
2508    E0456
2509    E1001
2510    E0438
2511    E1192
Name: student_id, Length: 2512, dtype: str>
<bound method IndexOpsMixin.nunique of 0                     Economía
1               Administración
2               Administración
3             Ciencia de Datos
4                       Diseño
                 ...
2507          Ciencia de Datos
2508            Administración
2509    Ingeniería de Sistemas
2510     Ingeniería Industrial
2511            Administración
Name: programa, Length: 2512, dtype: str>
<bound method IndexOpsMixin.nunique of 0       5
1       6
2       1
3       8
4       3
       ..
2507    1
2508    2
2509    1
2510    1
2511    2
Name: semestre, Length: 2512, dtype: int64>
<bound method IndexOpsMixin.nunique of 0       21
1       23
2       17
3       21
4       22
        ..
2507    18
2508    19
2509    19
2510    19
2511    20
Name: edad, Length: 2512, dtype: int64>
<bound method IndexOpsMixin.nunique of 0        Mujer
1        Mujer
2       Hombre
3        Mujer
4        Mujer
         ...
2507     Mujer
2508     Mujer
2509     Mujer
2510     Mujer
2511     Mujer
Name: genero, Length: 2512, dtype: str>
<bound method IndexOpsMixin.nunique of 0       16.8
1       23.5
2       12.6
3       15.7
4       20.5
        ...
2507    13.7
2508    17.7
2509    20.1
2510    15.5
2511    15.6
Name: horas_estudio_semana, Length: 2512, dtype: float64>
<bound method IndexOpsMixin.nunique of 0       5.5
1       7.2
2       6.7
3       6.1
4       6.4
       ...
2507    6.3
2508    5.8
2509    5.2
2510    7.8
2511    7.7
Name: horas_sueno_noche, Length: 2512, dtype: float64>
<bound method IndexOpsMixin.nunique of 0       61.0
1       98.0
2       55.0
3       57.0
4       50.0
        ...
2507    81.0
2508    47.0
2509    92.0
2510    50.0
2511    50.0
Name: tiempo_desplazamiento_min, Length: 2512, dtype: float64>
<bound method IndexOpsMixin.nunique of 0                Bus
1       TransMilenio
2       TransMilenio
3               Moto
4              Carro
            ...
2507       Caminando
2508       Caminando
2509       Caminando
2510    TransMilenio
2511       Caminando
Name: medio_transporte, Length: 2512, dtype: str>
<bound method IndexOpsMixin.nunique of 0       4
1       4
2       5
3       4
4       5
       ..
2507    5
2508    4
2509    5
2510    3
2511    3
Name: nivel_estres, Length: 2512, dtype: int64>
<bound method IndexOpsMixin.nunique of 0       4
1       4
2       4
3       3
4       4
       ..
2507    4
2508    4
2509    3
2510    4
2511    4
Name: satisfaccion_academica, Length: 2512, dtype: int64>
<bound method IndexOpsMixin.nunique of 0       3
1       2
2       3
3       1
4       5
       ..
2507    5
2508    3
2509    1
2510    5
2511    6
Name: dias_ejercicio_semana, Length: 2512, dtype: int64>
<bound method IndexOpsMixin.nunique of 0        7.2
1       10.8
2        6.8
3       14.3
4       11.0
        ...
2507     9.7
2508     4.9
2509     9.1
2510     3.7
2511    10.8
Name: horas_sociales_semana, Length: 2512, dtype: float64>
<bound method IndexOpsMixin.nunique of 0              A veces
1                Nunca
2              A veces
3                Nunca
4              A veces
             ...
2507    Frecuentemente
2508    Frecuentemente
2509    Frecuentemente
2510    Todos los días
2511           A veces
Name: uso_ia_generativa, Length: 2512, dtype: str>
<bound method IndexOpsMixin.nunique of 0       3
1       2
2       4
3       4
4       2
       ..
2507    3
2508    1
2509    4
2510    3
2511    4
Name: confianza_programando, Length: 2512, dtype: int64>
<bound method IndexOpsMixin.nunique of 0        Ingeniería de datos
1            No estoy seguro
2       Analítica de negocio
3       Analítica de negocio
4            No estoy seguro
                ...
2507    Analítica de negocio
2508                 IA y ML
2509    Analítica de negocio
2510    Analítica de negocio
2511           Visualización
Name: area_interes_datos, Length: 2512, dtype: str>
<bound method IndexOpsMixin.nunique of 0       Presencial
1       Presencial
2       Presencial
3       Presencial
4       Presencial
           ...
2507    Presencial
2508    Presencial
2509    Presencial
2510    Presencial
2511    Presencial
Name: modalidad_preferida, Length: 2512, dtype: str>
<bound method IndexOpsMixin.nunique of 0       3.47
1       3.69
2       3.26
3       2.90
4       3.54
        ...
2507    3.67
2508    3.24
2509    3.82
2510    3.79
2511    3.75
Name: promedio_acumulado, Length: 2512, dtype: float64>
<bound method IndexOpsMixin.nunique of 0       2026-08-01
1       2026-08-10
2       2026-08-21
3       2026-08-19
4       2026-08-04
           ...
2507    2026-08-10
2508    2026-08-04
2509    2026-08-19
2510    2026-08-11
2511    2026-08-02
Name: fecha_encuesta, Length: 2512, dtype: str>

In [ ]:
dimensiones =  "la tabla tiene 2512 obsrrvaciones y 19 variables de estudio"
tipos = "Todos tienen sentido, algunos son valores numericos o str sin embargo representan una variale de escala ordinal, y la fecha ya que deberia de usarse como un tipo datetime64"
faltantes = ""
duplicados = ""
cardinalidad = ""
distribucion = ""
columnas = ["dimensiones","tipos","faltantes","duplicados","cardinalidad","distribucion"]
preguntas = [0,0,0,0,0,0]
respuestas = [dimensiones,tipos,faltantes,duplicados,cardinalidad,distribucion]
dicc = {"Aspectos": columnas,
        "pregunta guia": preguntas,
        "respuesta": respuestas}

resp = pd.DataFrame(dicc, index = [1,2,3,4,5,6])
resp

,Aspectos,pregunta guia,respuesta
1,dimensiones,0,la tabla tiene 2512 obsrrvaciones y 19 variabl...
2,tipos,0,
3,faltantes,0,
4,duplicados,0,
5,cardinalidad,0,
6,distribucion,0,