A)
B)
C)
D)

In [53]:
import pandas as pd

In [65]:
df = pd.read_csv("estudiantes - copy.csv")

In [54]:
df.head()

             variables tipo_python    escala  descripcion         ejemplo
student_id  student_id         str   ordinal            0           E0456
programa      programa         str   Nominal            0  Administración
semestre      semestre       int64  continua            0               2
edad              edad       int64  continua            0              19
genero          genero         str   nominal            0           Mujer

In [55]:
df.tail()

,variables,tipo_python,escala,descripcion,ejemplo
confianza_programando,confianza_programando,int64,ordinal,0,1
area_interes_datos,area_interes_datos,str,nominal,0,IA y ML
modalidad_preferida,modalidad_preferida,str,ordinal,0,Presencial
promedio_acumulado,promedio_acumulado,float64,discreto,0,3.24
fecha_encuesta,fecha_encuesta,str,nominal,0,2026-08-04

In [56]:
df.shape

(19, 5)

In [57]:
df.columns

Index(['variables', 'tipo_python', 'escala', 'descripcion', 'ejemplo'], dtype='str')

In [58]:
tipo = df.dtypes
print(tipo)

variables         str
tipo_python    object
escala            str
descripcion     int64
ejemplo           str
dtype: object

In [67]:

escala = ["ordinal","Nominal","continua","continua","nominal","continua","continua","continua","nominal","ordinal","ordinal","discreto","discreto","ordinal","ordinal","nominal","ordinal","discreto","nominal"]

ejemplo = ["E0456","Administración","2","19","Mujer","17.7","5.8","47.0","Caminando","4","4","3","4.9","Frecuentemente","1","IA y ML","Presencial","3.24","2026-08-04"]
dcd = {
       "variables" : df.columns,
       "tipo_python":df.dtypes,
       "escala": escala,
       "descripcion": 0,
       "ejemplo": ejemplo}

ef = pd.DataFrame(dcd, index = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19] )
ef

,variables,tipo_python,escala,descripcion,ejemplo
1,student_id,NaN,ordinal,0,E0456
2,programa,NaN,Nominal,0,Administración
3,semestre,NaN,continua,0,2
4,edad,NaN,continua,0,19
5,genero,NaN,nominal,0,Mujer
6,horas_estudio_semana,NaN,continua,0,17.7
7,horas_sueno_noche,NaN,continua,0,5.8
8,tiempo_desplazamiento_min,NaN,continua,0,47.0
9,medio_transporte,NaN,nominal,0,Caminando
10,nivel_estres,NaN,ordinal,0,4
11,satisfaccion_academica,NaN,ordinal,0,4
12,dias_ejercicio_semana,NaN,discreto,0,3
13,horas_sociales_semana,NaN,discreto,0,4.9
14,uso_ia_generativa,NaN,ordinal,0,Frecuentemente
15,confianza_programando,NaN,ordinal,0,1
16,area_interes_datos,NaN,nominal,0,IA y ML
17,modalidad_preferida,NaN,ordinal,0,Presencial
18,promedio_acumulado,NaN,discreto,0,3.24
19,fecha_encuesta,NaN,nominal,0,2026-08-04

In [22]:
df.isnull().sum()

student_id                    0
programa                      0
semestre                      0
edad                          0
genero                        0
horas_estudio_semana          0
horas_sueno_noche            72
tiempo_desplazamiento_min    56
medio_transporte              0
nivel_estres                  0
satisfaccion_academica        0
dias_ejercicio_semana         0
horas_sociales_semana         0
uso_ia_generativa             0
confianza_programando         0
area_interes_datos           41
modalidad_preferida           0
promedio_acumulado            0
fecha_encuesta                0
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(12)

In [76]:
dimensiones = df.shape
tipos = ""
faltantes = ""
duplicados = ""
cardinalidad = ""
distribucion = ""
columnas = ["dimensiones","tipos","faltantes","duplicados","cardinalidad","distribucion"]
preguntas = [0,0,0,0,0,0]
respuestas = [dimensiones,tipos,faltantes,duplicados,cardinalidad,distribucion]
dicc = {"Aspectos": columnas,
        "pregunta guia": preguntas,
        "respuesta": respuestas}

resp = pd.DataFrame(dicc, index = [1,2,3,4,5,6])
resp

       Aspectos  pregunta guia   respuesta
1   dimensiones              0  (2512, 19)
2         tipos              0
3     faltantes              0
4    duplicados              0
5  cardinalidad              0
6  distribucion              0